### ISSUE TITLE
Support Webpack development mode

### ISSUE THREAD

**Issue by dunnkers** [fossamagna/gas-webpack-plugin#135]
Currently only works when `mode` is `production`. Can we also support `mode: develompent`?

**Comment by fossamagna** [comment]
@dunnkers 
Please try set `none` to [devtool](https://webpack.js.org/configuration/devtool/#devtool) at webpack.config.js or cli options. In `development` mode, webpack is using eval function. So, gas-webpack-plugin cannot detect a function assignment expression to global object.

**Comment by dunnkers** [comment]
Will try later and let you know what happened, thanks!
