### ISSUE TITLE
Issue with Production mode

### ISSUE THREAD

**Issue by labnol** [fossamagna/gas-webpack-plugin#208]
The top level functions are not generated when the mode is set to production. It works fine for 'none' mode.

**Comment by fossamagna** [comment]
@labnol Thank you for your report. Do you have the source code to reproduce the problem?

**Comment by labnol** [comment]
@fossamagna - here's how you can reproduce the issue:

`git clone https://github.com/labnol/website-monitor`
`cd website-monitor`
`npm install`
`npx webpack` (works fine)
`npx webpack --mode production` (top level functions are not generated)

**Comment by fossamagna** [comment]
@labnol I tried build website-monitor on production mode. I could be reproduced issue too.
This problem contains from gas-webpack-plugin@1.0.0.
workaround. Please downgrade to gas-webpack-plugin@0.3.0.
I will try fix to this issue at this weekend.

**Comment by labnol** [comment]
@fossamagna - thank you for all the good work you are doing!
