### ISSUE TITLE
Does your script support classes

### ISSUE THREAD

**Issue by barecool** [fossamagna/gas-webpack-plugin#466]
i am using the latest version of your script 
but cannot get it to work with classes 
i suspect it does not support it

**Comment by fossamagna** [comment]
@barecool Thank you for your report.
Can I have the source codes, webpack config, etc (repository) to reproduce your issue.

**Comment by barecool** [comment]
I do not have a public repo at the moment that I can post publicly the code 

It is a project using vue 2.x 
And the back end is apps script. 
I’ll try in put some thing together 
Later as an example 
Sorry 

I’m kinda lost on the setup using classes 
And assigning them to global 
As the examples don’t show this 
Hence my request

**Comment by barecool** [comment]
can be closed  - working as expected
