### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by labnol** [fossamagna/gas-webpack-plugin#516]
I noticed an issue with the production mode. The top-level function is not added to the output if the global function calls another method that is imported from another folder.

I tried to replicate the structure here if that explains it better. https://codesandbox.io/s/mystifying-mestorf-8dfec?file=/src/index.js

**Comment by labnol** [comment]
Update: The problem disappears if the mode is set to 'none' in webpack configuration.

**Comment by fossamagna** [comment]
@labnol Thank you. 
I consider that this issue occur using `production` mode and using ES Module.
I still want to find the cause based on the source code you provided.

**Comment by labnol** [comment]
Please see this [test repo](https://github.com/labnol/testing). The top-level function is not generated when the mode is production but works for 'none' - thanks!

**Comment by labnol** [comment]
Found another issue I guess. This doesn't work.

```js
const fnName = "hello";
global[fnName] = () => console.log("do something..");
```

**Comment by fossamagna** [comment]
@labnol issue for Property accessors is moved #520

**Comment by fossamagna** [comment]
@labnol  A new version is now available. Try it out.
https://www.npmjs.com/package/gas-webpack-plugin/v/2.0.1
