### ISSUE TITLE
Default includePatterns broken in v2.2.0

### ISSUE THREAD

**Issue by JJPell** [fossamagna/gas-webpack-plugin#695]
Hi,

The plugin is broken for my when using v2.2.0 and I believe I've traced the issue down to this line:

```js
    if (!this.includePatterns.some(file => minimatch(module.resource, file))) {
      return;
    }
```

For me it seems to be skipping all files as minimatch isn't matching files using the default include pattern.

I believe this is due to upgrading minimatch from `v3.0.4` to `v5.0.0` after testing the following in minimatch in both versions:

```js
const minimatch = require('minimatch');

const resource = "C:\\Foo\\Bar.js";
const patten = "C:\\Foo\\**\\*";

const result = minimatch(resource, patten);

// v3.0.4 -> result = true;
// v5.0.0 -> result = false;
```

I'm using Windows so I'm not sure if this is a windows only issue.

**Comment by fossamagna** [comment]
@JJPell Thank you for your feedback.
I published [v2.2.1](https://www.npmjs.com/package/gas-webpack-plugin/v/2.2.1). Please try it.
