### ISSUE TITLE
Compiler errors with autoGlobalExportsFiles and webpack 5

### ISSUE THREAD

**Issue by enuchi** [fossamagna/gas-webpack-plugin#719]
Hi @fossamagna, thanks for the work on this very useful plugin.

I've been trying to upgrade to webpack 5 and running into issues with `autoGlobalExportsFiles` config. It looks as though the "global" assignments are incorrectly being inserted into the webpack file.

I noticed when I take out this line, it works fine: https://github.com/fossamagna/gas-webpack-plugin/blob/dc5c4b229bdc4900898fc93c2e66f5974c83b2e1/index.js#L86

Here is my bundled file after I remove that line from this plugin. Interestingly, the code works fine if this line is left out -- I can still run this code in a spreadsheet and the global functions are found correctly:
<img width="487" alt="Screen Shot 2022-06-12 at 11 56 14 AM" src="https://user-images.githubusercontent.com/31550519/173242373-eba50465-5a10-4792-8adf-e2f750cad51a.png">

And here it is with that line left in. Notice the insertion is not happening in the right place.
<img width="644" alt="Screen Shot 2022-06-12 at 11 56 47 AM" src="https://user-images.githubusercontent.com/31550519/173242426-0a993d7a-5fa7-4548-989d-0762310c9463.png">

Any ideas what might be causing this?

**Comment by SeraClinic** [comment]
I'm experiencing exactly same issue with autoGlobalExportsFiles  option as @enuchi reported

**Comment by fossamagna** [comment]
@enuchi Thank you for your repo. I can reproduce this issue.
I will address this issue.

**Comment by fossamagna** [comment]
@enuchi @SeraClinic 

I have yet to find the root cause. However, the `mode: none` setting in `webpack.config.js` seems to be affecting this issue.
As a workaround, changing `webpack.config.js` as follows seems to prevent the issue.

- Use `production` mode.
- Set `false` to `optimization.minimize` (Optional, if you no need minify)

**Comment by enuchi** [comment]
Hi @fossamagna, thanks again for looking into this issue.

Unfortunately changing to `production` mode didn't work fully for me. When I try running the build in `production` mode, the generated code seems correct in the sample repo (that is, no variables are being cut off), but when I try to run the script in the spreadsheet it still errors out. I tried running the build in `production` mode in a separate project that has a lot more functions, and the "global" assignments are still being inserted in the middle of a variable string, so it may just be an accident in the minimal repo that it "looks" correct in `production` mode.

The only way I could get it to work here is if I manually fix the generated code so that the "global" assignments are not cutting off any variables.

**Comment by fossamagna** [comment]
@enuchi Thank you for your feedback.
I published [gas-webpack-plugin@2.2.2-beta.0](https://www.npmjs.com/package/gas-webpack-plugin/v/2.2.2-beta.0). Would you be willing to try it?
I changed position of "global" assignments in this release.

**Comment by fossamagna** [comment]
Hi @enuchi @SeraClinic 
I published [gas-webpack-plugin@2.2.2](https://www.npmjs.com/package/gas-webpack-plugin/v/2.2.2).

**Comment by SeraClinic** [comment]
Much appreciate for your hard work!! :)
