### ISSUE TITLE
`autoGlobalExportsFiles` not working with ECMAScript

### ISSUE THREAD

**Issue by sharky98** [fossamagna/gas-webpack-plugin#794]
Hello,

Today I was trying to make this plugin work with the `autoGlobalExportsFiles` settings. I tend to always use the "latest and greatest" version of any packages; and this may be my pitfall here.

Anyway, here a code that is working fine in GAS; but the `autoGlobalExportsFiles` do nothing (I still need to put the `global.[fct] = fct` in my code). I created a repo that replicate this: https://github.com/sharky98/es2022-gas-webpack-plugin-bug.

In there you'll see in [dist](https://github.com/sharky98/es2022-gas-webpack-plugin-bug/tree/main/dist) folder the three output I got. You'll also have the webpack config, and tsconfig.

Note: I am using TypeScript 5, with array extends; which mean I need to use the current main for ts-node; the tgz is included in the repo, with the right config from package.json.

Note 2: I am not too familiar with webpack config and tsconfig... Just enough to make it work for me. So, feel free to tell me what I miss.

Note 3: I added you as collaborators on that repo; feel free to commit to it for any correction/test/etc.

Thanks

**Comment by sharky98** [comment]
Side note, when using indexer access (`global["doGet"] = doGet;`), the plugin will fail to retrieve the name and output `function undefined() {}` instead.

**Comment by fossamagna** [comment]
@sharky98 Thanks for your feedback and for sharing the repository that reproduces this issue.
Perhaps this is a bug in gas-webpack-plugin (or gas-entry-generator).
I will address on resolving this issue in the next few days.

**Comment by sharky98** [comment]
Thank you very much. I'll try it probably next week.

**Comment by sharky98** [comment]
It works perfectly!

I did add two other use cases in my repo, one that works and one that isn't. They are more edge case situation I would say, nice to have.

The one not working is when doing a named export of a `const` function inside the declaration and not as an export list like below.

I'll leave it to you to close this issue or leave it open for this "nice to have" second part.

```ts
export const doGet = () => {
  const title = "Google Apps Script";
  const fileName = "index.html";
  return HtmlService.createHtmlOutputFromFile(fileName)
    .setTitle(title)
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.DEFAULT);
};
```

Thank you very much again!
